# Generated by Django 4.1.1 on 2022-10-12 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0002_blogsrionegro_alter_blogssalta_cuerpo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogsMendoza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('subtitulo', models.CharField(max_length=100)),
                ('cuerpo', models.CharField(max_length=1000)),
                ('autor', models.CharField(max_length=40)),
                ('fecha', models.CharField(max_length=40)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blogmendoza')),
            ],
        ),
    ]
